version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass JQODI9u1uioasdjkl][]12039dasjkl!@((Adlakjsdl))
    volumes:
      - cache:/data
  express_api:
    build:
      context: ./src
    ports:
      - 3000:3000
    depends_on:
      - db
      - cache
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=JQODI9u1uioasdjkl][]12039dasjkl!@((Adlakjsdl))
volumes:
  db:
    driver: local