
# @name hello_world
GET {{protocol}}://{{domain}}

###
# @name forbidden
GET {{protocol}}://{{domain}}/ohashljk

###
# @name create_post
POST {{protocol}}://{{domain}}/posts
content-type: application/json

{
    "frank":"murphy",
    "title":"poop"
}